apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
spec:
  replicas: {{ .Values.core.replicaCount }}
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: core-service
          image: {{ .Values.core.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.core.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: FILE_SERVICE_URL
              value: "http://file-service:{{ .Values.file.port }}"
            - name: JWT_SECRET
              value: {{ .Values.jwtSecret | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  selector:
    app: core-service
  ports:
    - port: {{ .Values.core.port }}
      targetPort: {{ .Values.core.port }}
