apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: scms.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: {{ .Values.gateway.port }}
