stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-B -ntp"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests clean package

test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - mvn $MAVEN_CLI_OPTS test
